### ISSUE TITLE
How to deploy app?

### ISSUE THREAD

**Issue by tkonopelski** [cecicifu/SATRepairCRM#1]
I started the migration, which was generally successful:
`php bin/console doctrine:migrations:migrate`

But after running app in webbrowser I see error:
An exception has been thrown during the rendering of a template ("Asset manifest file ".../public/build/manifest.json" does not exist.").
I understand it has something to do with "yarn".
What to do next?

**Comment by cecicifu** [comment]
Hi, I just updated the project with the fix. a9a364173b017d4c65e83b4327ca1c10afa203f9

Update it or download again and do:
`npm install`
`npm run dev`

Thanks you! 😊

**Comment by tkonopelski** [comment]
Thank you. I should have guessed ;)

To see app in webbrowser I have to run:
`php bin/console doctrine:fixtures:load`
To load user and sample clients.

Nice work. I'll be doing something similar but I just have different dependencies between the products.

Btw: I used MySql rather than Postgresql, nevertheless everything went smoothly.
